name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Required by actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Build uses your package.json script:
      # "build": "contentlayer build && next build && next export"
      - name: Build static site
        run: npm run build

      # Optional but recommended: prevent Jekyll processing (underscored paths, etc.)
      - name: Add .nojekyll
        run: touch ./out/.nojekyll

      Optional: custom domain (preferred approach is to keep a CNAME file in /public)
      - name: Add CNAME
        if: ${{ env.CUSTOM_DOMAIN != '' }}
        run: echo "$CUSTOM_DOMAIN" > ./out/CNAME
        env:
          CUSTOM_DOMAIN: irchaos.club

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
